services:
  master:
    image: master-node # para localhost - build: .
    ports:
      - "8000:8000"
    expose:
      - 8000
    environment:
      - PYTHONUNBUFFERED=1
      - FLASK_ENV=development
      - BROKER_ADDRESS=localhost
      - NETWORK_INTERFACE=wlan0
    network_mode: "host"
    privileged: true
  mqtt:
    image: arm64v8/eclipse-mosquitto:1.6 # para localhost - image: eclipse-mosquitto:1.6
    container_name: mqtt
    expose:
      - 1883
    ports:
      - 1883:1883
    restart: unless-stopped
    network_mode: "host"
    privileged: true

networks:
  master-network:
    name: rsa-network
    driver: bridge