services:
  slave1:
    build: .
    ports:
      - "8001:8001"
    environment:
      - PYTHONUNBUFFERED=1
      - FLASK_ENV=development
    networks:
      - slave-network
  slave2:
    build: .
    ports:
      - "8002:8002"
    environment:
      - PYTHONUNBUFFERED=1
      - FLASK_ENV=development
    networks:
      - slave-network

networks:
 slave-network:
    external: true
    name: rsa-network