services:
  slave:
    image: slave-node # para localhost - build: .
    environment:
      - PYTHONUNBUFFERED=1
      - FLASK_ENV=development
      - BROKER_IP=10.1.1.1
      - NETWORK_INTERFACE=wlan0
    network_mode: "host"
    privileged: true