services:
  slave1:
    image: slave-node
    ports:
      - "8001:8001"
    environment:
      - PYTHONUNBUFFERED=1
      - FLASK_ENV=development
    networks:
      - slave-network
    privileged: true

networks:
 slave-network:
    external: true
    name: rsa-network